# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2

defaults: &defaults
  working_directory: ~/project/dclone
  docker:
    - image: circleci/node:8

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1.1-{{ .Branch }}-{{ checksum "package.json" }}
            - v1.1
      - run:
          command: |
            npm install --registry=https://registry.npm.taobao.org/
      - save_cache:
          paths:
            - node_modules/
          key: v1.1-{{ .Branch }}-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - dclone

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm run test

workflows:
  version: 2
  install-and-parallel-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
